### PR TITLE
Updated references in the documents from docs.microsoft.com - to learn

### PR DESCRIPTION
**Pull request by ElYusubov**
Updated references in the documents from docs.microsoft.com - to learn.

# Overview/Summary

This PR has updates to the references in the documentation.
It updates the reference links from docs.microsoft.com - to learn.microsoft.com

## This PR fixes/adds/changes/removes

1. This PR changes/updates the document urls to the latest source of information.

### Breaking Changes

1. No breaking changes

## Testing Evidence

Replace this with any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

## As part of this Pull Request I have

- [X] Read the [Contribution Guide](https://github.com/Azure/ALZ-Bicep/wiki/Contributing) and ensured this PR is compliant with the guide
- [ ] Ensured the resource API versions in `.bicep` file/s I am adding/editing are using the latest API version possible
- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/ALZ-Bicep/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/ALZ-Bicep/issues)
- [ ] *(ALZ Bicep Core Team Only)* Associated it with relevant [ADO Items](https://aka.ms/alz/bicep/backlog)
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/ALZ-Bicep/tree/main)
- [ ] Performed testing and provided evidence.
- [ ] Updated one or more of the following tests *(if required)*
  - [Unit](https://github.com/Azure/ALZ-Bicep/blob/main/.github/workflows/bicep-build-to-validate.yml)
  - [Linting](https://github.com/Azure/ALZ-Bicep/tree/main/.github/workflows)
  - [E2E (End-To-End)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/bicep-build-to-validate.yml)
  - [ValidateAzCloud (Base validation in Azure Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/base-unit-validate.yml)
  - [ValidateMcCloud (Base validation in Azure China Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/mc-base-unit-validate.yml)
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Module READMEs, Wiki Docs etc.)
- [ ] If relevant, created or updated Code Tours [here](https://github.com/Azure/ALZ-Bicep/blob/main/.vscode/tours)

### CODE REVIEW

**Review by jtracey93 — CHANGES_REQUESTED** [review]
Hey @ElYusubov,

Thanks for the PR, can you resolve the issues from the PR checks/tests in a new commit?

Let us know if you need a hand, but installing the EditorConfig VS Code extension and opening each of the failing files should resolve the issues.

**Comment by ElYusubov** [comment]
Thanks for checking @jtracey93!
I have EditorConfig for VS Code is installed on my laptop. Looking into the conflict now.

**Comment by ElYusubov** [comment]
Just pushed a commit to resolve super-linter issue, by opening & closing files that have errors on a linter stage.

**Review by jtracey93 — APPROVED** [review]
Thanks @ElYusubov LGTM

**Pull request merged**
