### PR TITLE
Issue forms

### PR DESCRIPTION
**Pull request by jhajduk-microsoft**
First draft of Issue Forms for bugs, features, and general feedback

Replace this with a brief description of what this Pull Request fixes, changes, etc.

## This PR fixes/adds/changes/removes

1. Creation of the forms for bugs, features, and general feedback

### Breaking Changes

N/A

## Testing Evidence

Replace this with any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://github.com/Azure/ALZ-Bicep/wiki/Contributing) and ensured this PR is compliant with the guide
- [x] Ensured the resource API versions in `.bicep` file/s I am adding/editing are using the latest API version possible
- [x]  Checked for duplicate [Pull Requests](https://github.com/Azure/ALZ-Bicep/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/ALZ-Bicep/issues)
- [x] *(ALZ Bicep Core Team Only)* Associated it with relevant [ADO Items](https://aka.ms/alz/bicep/backlog)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/ALZ-Bicep/tree/main)
- [ ] Performed testing and provided evidence.
- [ ] Updated one or more of the following tests *(if required)*
  - [Unit](https://github.com/Azure/ALZ-Bicep/blob/main/.github/workflows/bicep-build-to-validate.yml)
  - [Linting](https://github.com/Azure/ALZ-Bicep/tree/main/.github/workflows)
  - [E2E (End-To-End)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/bicep-build-to-validate.yml)
  - [ValidateAzCloud (Base validation in Azure Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/base-unit-validate.yml)
  - [ValidateMcCloud (Base validation in Azure China Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/mc-base-unit-validate.yml)
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Module READMEs, Wiki Docs etc.)
- [ ] If relevant, created or updated Code Tours [here](https://github.com/Azure/ALZ-Bicep/blob/main/.vscode/tours)

### CODE REVIEW

**Review by jtracey93 — CHANGES_REQUESTED** [review]
Hey @jhajduk-microsoft,

Thanks for the PR. Can you fix the linter errors please? https://github.com/Azure/ALZ-Bicep/actions/runs/5327851749/jobs/9651792603?pr=562#step:4:88

Should be as simple as opening each of the files in VSCode and <kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>F</kbd>

> make sure you have the editorconfig extension installed

Save each file and commit and push :)

**Review by jtracey93 — CHANGES_REQUESTED** [review]
Thanks @jhajduk-microsoft, do we need to remove the current issue templates as well in this PR?

**Comment by jhajduk-microsoft** [comment]
@jtracey93 - Lets see how the new forms work in the repo and then I will submit a subsequent PR to remove the old forms

**Review by jtracey93 — APPROVED** [review]

**Pull request merged**
