### PR TITLE
Adding RBAC constrained delegation parameters and guidance in the roleAssignment modules

### PR DESCRIPTION
**Pull request by sebassem**
Adding the conditions parameters to the roleAssignment modules with examples and guidance to enable customers to securely delegate role assignments.

## Related Issues/Work Items

Fixes AB#36173

### Breaking Changes

N/A

## Testing Evidence

image

image

## As part of this Pull Request I have

- [X] Read the [Contribution Guide](https://github.com/Azure/ALZ-Bicep/wiki/Contributing) and ensured this PR is compliant with the guide
- [X] Ensured the resource API versions in `.bicep` file/s I am adding/editing are using the latest API version possible
- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/ALZ-Bicep/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/ALZ-Bicep/issues)
- [X] *(ALZ Bicep Core Team Only)* Associated it with relevant [ADO Items](https://aka.ms/alz/bicep/backlog)
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/ALZ-Bicep/tree/main)
- [X] Performed testing and provided evidence.
- [ ] Updated one or more of the following tests *(if required)*
  - [Unit](https://github.com/Azure/ALZ-Bicep/blob/main/.github/workflows/bicep-build-to-validate.yml)
  - [Linting](https://github.com/Azure/ALZ-Bicep/tree/main/.github/workflows)
  - [E2E (End-To-End)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/bicep-build-to-validate.yml)
  - [ValidateAzCloud (Base validation in Azure Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/base-unit-validate.yml)
  - [ValidateMcCloud (Base validation in Azure China Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/mc-base-unit-validate.yml)
- [X] Updated relevant and associated documentation (e.g. Contribution Guide, Module READMEs, Wiki Docs etc.)
- [ ] If relevant, created or updated Code Tours [here](https://github.com/Azure/ALZ-Bicep/blob/main/.vscode/tours)

### CODE REVIEW

**Review by jtracey93 — APPROVED** [review]
LGTM

@sebassem great work. Just to confirm we aren't adding the condition building simplification to these modules right, just the sub vending ones?

**Comment by sebassem** [comment]
> LGTM
> 
> @sebassem great work. Just to confirm we aren't adding the condition building simplification to these modules right, just the sub vending ones?

Correct, just showing how to use the condition parameter in the roleAssignment modules

**Comment by oZakari** [comment]
@sebassem Im looking into that pipeline error but it's unrelated to your changes so nothing to do on your end.

**Comment by oZakari** [comment]
@sebassem Looking into it closer, it is related to these changes. 😞 The policy assignment management group module references the role assignment modules. In main currently, json is approx 3.4 MB and with your changes it comes out to 4.2 MB. As far as I'm aware the only way we can get around this is by splitting up the module deployments (likely the ALZ Default Policy Assignments module). However, I'd rather avoid this if at all possible due to it being messy and requiring a lot of work and primarily with the AVM transition work in play.

**Comment by oZakari** [comment]
If I remove the customer telemetry module references, I can get it down to 3.5 MB. Easiest thing I can think of without messing with a bunch of other stuff. Will think on it a bit more and update here. Ping me if any options come to your mind as well.

**Comment by sebassem** [comment]
> If I remove the customer telemetry module references, I can get it down to 3.5 MB. Will think on it a bit more and update here but thinking that's going to be the easiest/quickest option. Ping me if any options come to your mind as well.

Maybe its the long description of the parameter. I just pushed a commit to reduce the description, if that solved it, then I can move the instructions to generate a condition in md file ?

image

**Comment by oZakari** [comment]
Awesome. thanks! That got us to 4.011 and tested locally and no error so let's go with that approach for now. 

I am going to hit it again with the policy refresh, but good enough for now.

**Comment by sebassem** [comment]
> Awesome. thanks! That got us to 4.011 and tested locally and no error so let's go with that approach for now.
> 
> I am going to hit it again with the policy refresh, but good enough for now.

Just pushed the changes with having the instructions in the readme

**Review by oZakari — APPROVED** [review]

**Pull request merged**
