### PR TITLE
ALZ bicep modules multi-region guidance

### LINKED ISSUE #375: 💡 Feature Request - Multi-Region ALZs
Per this https://learn.microsoft.com/en-gb/azure/cloud-adoption-framework/ready/enterprise-scale/faq#how-do-we-enable-more-azure-regions-when-we-use-azure-landing-zone-architecture

Could additional functionality be extended to accommodate multi-region ALZs (platform and workloads) scenarios where customer wants to deploy n regions and have things plumbed correctly per region base for example, diagnostics set to their regional LAW, hubs peered between them etc. although AAD logs would only go to 1 LAW since it is not regional. 

@danycontre  per our chat

### PR DESCRIPTION
**Pull request by sebassem**
# Overview/Summary

This PR is adding examples and guidance on how to deploy ALZ platform resources into multiple regions. It covers hub and spoke and vwan modules

## This PR fixes/adds/changes/removes

Closes #375 

### Breaking Changes

None

## Testing Evidence

This PR only has readme changes

## As part of this Pull Request I have

- [X] Read the [Contribution Guide](https://github.com/Azure/ALZ-Bicep/wiki/Contributing) and ensured this PR is compliant with the guide
- [X] Ensured the resource API versions in `.bicep` file/s I am adding/editing are using the latest API version possible
- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/ALZ-Bicep/pulls)
- [X] Associated it with relevant [GitHub Issues](https://github.com/Azure/ALZ-Bicep/issues)
- [] *(ALZ Bicep Core Team Only)* Associated it with relevant [ADO Items](https://aka.ms/alz/bicep/backlog)
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/ALZ-Bicep/tree/main)
- [X] Performed testing and provided evidence.
- [X] Updated one or more of the following tests *(if required)*
  - [Unit](https://github.com/Azure/ALZ-Bicep/blob/main/.github/workflows/bicep-build-to-validate.yml)
  - [Linting](https://github.com/Azure/ALZ-Bicep/tree/main/.github/workflows)
  - [E2E (End-To-End)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/bicep-build-to-validate.yml)
  - [ValidateAzCloud (Base validation in Azure Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/base-unit-validate.yml)
  - [ValidateMcCloud (Base validation in Azure China Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/mc-base-unit-validate.yml)
- [X] Updated relevant and associated documentation (e.g. Contribution Guide, Module READMEs, Wiki Docs etc.)
- [ ] If relevant, created or updated Code Tours [here](https://github.com/Azure/ALZ-Bicep/blob/main/.vscode/tours)

### CODE REVIEW

**Comment by sebassem** [comment]
@oZakari @jtracey93 This is a still a WIP but wanted to share an early draft of the _hubNetworking_ multi-region guidance. Please let me know if you have comments/feedback so I can start on the _vWan_ module next.

**Comment by sebassem** [comment]
This PR is dependent on https://github.com/Azure/ALZ-Bicep/pull/805

**Review by oZakari — CHANGES_REQUESTED** [review]
Hey Seif, I think the docs are concise and clear. I have made some updates to the hub networking module, particularly with switching to East US and West US since they are paired regions. Also, demonstrates that they will need to look out for the regions that do/dont support availability zones to determine which parameter file to use.

I also removed the example parameter files to avoid bloat as I think it should be pretty easy to follow that they just need to change the regions. Let me know if you object though and we can discuss.

Could you please update the East US 2 example output to West US? After that I think it is good to merge.

**Comment by sebassem** [comment]
> Hey @sebassem, I think the docs are concise and clear. I have made some updates to the hub networking module readme, particularly with switching to East US and West US since they are paired regions. Also, demonstrates that they will need to look out for the regions that do/dont support availability zones to determine which parameter file to use.
> 
> I also removed the example parameter files to avoid bloat as I think it should be pretty easy to follow that they just need to change the regions. Let me know if you object though and we can discuss.
> 
> Could you please update the East US 2 example output to West US? After that I think it is good to merge as long as good on your end.

Thanks Zach, screenshot has been updated

**Review by oZakari — APPROVED** [review]

**Pull request merged**
