### PR TITLE
VPN Gateway P2S support

### PR DESCRIPTION
**Pull request by juang903**
# Overview/Summary

Adds support for configuring P2S connections in the VPN gateway

## This PR fixes/adds/changes/removes

1. Adds the option to configure P2S VPN connections

## Testing Evidence

Tested by deploying config for AAD, Certificate, and Radius authentication.

### CODE REVIEW

**Comment by juang903** [comment]
I have some sample parameters that I would like to add, but not sure where this is best documented. Please advise. 
The sample parameters are for vpnClientConfiguration in hubNetworking.parameters.all.json. Here is an example for AAD auth...
`     "vpnClientConfiguration": {
          "vpnClientAddressPool": {
            "addressPrefixes": [
              "172.16.0.0/24"
            ]
          },
          "vpnClientProtocols": [
            "OpenVPN"
          ],
          "vpnAuthenticationTypes": [
            "AAD"
          ],
          "aadTenant": "https://login.microsoftonline.com/**My-Tenant-ID**",
          "aadAudience": "41b23e61-6c1e-4545-b367-cd054e0ed4b4",
          "aadIssuer": "https://sts.windows.net/**My-Tenant-ID**/"
        }`

**Comment by jtracey93** [comment]
@juang903 consider adding them to the readme in the parameters section like we did for management groups: https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/modules/managementGroups#parameters

**Comment by juang903** [comment]
@jtracey93 Thanks. I added an example of how to set this config in the readme.

**Review by oZakari — APPROVED** [review]
Fixed some minor linting issues, but everything else looks good to me! Thank you for your contribution, @juang903!

**Pull request merged**
