### PR TITLE
Update containerRegistry API version

### PR DESCRIPTION
**Pull request by bartlannoeye**
# Overview/Summary
Addendum for #247

Updated ACR API version from preview to the latest stable as it was giving a deploy error. 

```
/home/vsts/work/1/s/infra-as-code/bicep/CRML/containerRegistry/containerRegistry.bicep(29,76) : Error use-recent-api-versions: Use more recent API version for 'Microsoft.ContainerRegistry/registries'. '2022-02-01-preview' is a preview version and there is a more recent non-preview version available. Acceptable versions: 2023-01-01-preview, 2022-12-01, 2021-09-01 [https://aka.ms/bicep/linter/use-recent-api-versions]
/home/vsts/work/1/s/infra-as-code/bicep/orchestration/governanceacr/governanceacr.bicep(34,34) : Error BCP104: The referenced module has errors.
##[error]Script failed with exit code: 1
```

## This PR fixes/adds/changes/removes

1. containerRegistry API version

## Testing Evidence

image

## As part of this Pull Request I have

- [X] Read the [Contribution Guide](https://github.com/Azure/ALZ-Bicep/wiki/Contributing) and ensured this PR is compliant with the guide
- [X] Ensured the resource API versions in `.bicep` file/s I am adding/editing are using the latest API version possible
- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/ALZ-Bicep/pulls)
- [X] Associated it with relevant [GitHub Issues](https://github.com/Azure/ALZ-Bicep/issues)
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/ALZ-Bicep/tree/main)
- [X] Performed testing and provided evidence.

### CODE REVIEW

**Review by jtracey93 — CHANGES_REQUESTED** [review]
Thanks @bartlannoeye again for this.

Fancy also doing the same for `Microsoft.Network/virtualNetworkGateways` in the hubNetworking module as your tests on this PR are failing due to this also.

Let me know 👍

**Comment by bartlannoeye** [comment]
@jtracey93 I had a quick look at the error, looks like my network deployment on Tuesday was just in time :). I'll update the templates and let the tests have another go at it here.

    '2021-02-01' is 731 days old, should be no more than 730 days old

**Review by jtracey93 — APPROVED** [review]
LGTM

**Pull request merged**
