### PR TITLE
fix: General networking fixes and add active-active capability for vnet gateway

### LINKED ISSUE #561: 🪲 Bug Report - Support for active/active VNET Gateway
## Describe the bug

ActiveActive Gateway must be created with two IP configurations. (Code: ActiveActiveGatewayMustHaveExactlyTwoIpConfigurations)

## To Reproduce

Steps to reproduce the behaviour:

config\custom-parameters\hubNetworking.parameters.all.json
"parVpnGatewayConfig": {
      "value": {
"activeActive": true
        }

## Expected behaviour
upstream-releases\v0.14.0\infra-as-code\bicep\modules\hubNetworking\hubNetworking.bicep

Wanting to confirm module support for active/active configuration

## Correlation ID

363500a8-01bc-4772-807c-4587532bfb04

## Additional context

Anything else we should know to help us troubleshoot this bug?

### PR DESCRIPTION
**Pull request by oZakari**
# Overview/Summary

This pull request includes several updates to the `infra-as-code/bicep/modules/hubNetworking/hubNetworking.bicep` file to upgrade the API versions of various Azure resources and add support for active-active configurations for gateways.

### API Version Upgrades:
* Updated API versions for `resBastionSubnetRef`, `resBastionNsg`, `resBastion`, `resGatewaySubnetRef`, `resAzureFirewallSubnetRef`, `resAzureFirewallMgmtSubnetRef`, `resFirewallPolicies`, `resAzureFirewall`, and `resHubRouteTable` to `2024-01-01`. [[1]](diffhunk://#diff-6f15d7e8d605ac4753479b21282427b592dfde471ef345500fc2dbd050c2f422L540-R545) [[2]](diffhunk://#diff-6f15d7e8d605ac4753479b21282427b592dfde471ef345500fc2dbd050c2f422L707-R707) [[3]](diffhunk://#diff-6f15d7e8d605ac4753479b21282427b592dfde471ef345500fc2dbd050c2f422L743-R743) [[4]](diffhunk://#diff-6f15d7e8d605ac4753479b21282427b592dfde471ef345500fc2dbd050c2f422L823-R868) [[5]](diffhunk://#diff-6f15d7e8d605ac4753479b21282427b592dfde471ef345500fc2dbd050c2f422L871-R911) [[6]](diffhunk://#diff-6f15d7e8d605ac4753479b21282427b592dfde471ef345500fc2dbd050c2f422L910-R950) [[7]](diffhunk://#diff-6f15d7e8d605ac4753479b21282427b592dfde471ef345500fc2dbd050c2f422L1023-R1063)

### Gateway Configuration Enhancements:
* Added support for active-active gateway configurations by creating a second public IP if the gateway is active-active.
* Modified `ipConfigurations` to include a secondary IP configuration when `activeActive` is true.

### Conditional Outputs:
* Updated the `outDdosPlanResourceId` output to conditionally return an empty string if DDoS protection is not enabled.

## Related Issues/Work Items

Fixes #561
Fixes [AB#35815](https://dev.azure.com/CSUSolEng/2a9d5a5a-8998-4ad0-81c8-ef3045e4da97/_workitems/edit/35815)

## This PR fixes/adds/changes/removes

1. Adds the capability to support active-active virtual network gateway configuration
2. Fixes issues with parDDosId when parDDosEnabled is set to false.
3. Updates hub networking module api versions

### Breaking Changes

None

## Testing Evidence

Replace this with any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://github.com/Azure/ALZ-Bicep/wiki/Contributing) and ensured this PR is compliant with the guide
- [x] Ensured the resource API versions in `.bicep` file/s I am adding/editing are using the latest API version possible
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/ALZ-Bicep/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/ALZ-Bicep/issues)
- [x] *(ALZ Bicep Core Team Only)* Associated it with relevant [ADO Items](https://aka.ms/alz/bicep/backlog)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/ALZ-Bicep/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated one or more of the following tests *(if required)*
  - [Unit](https://github.com/Azure/ALZ-Bicep/blob/main/.github/workflows/bicep-build-to-validate.yml)
  - [Linting](https://github.com/Azure/ALZ-Bicep/tree/main/.github/workflows)
  - [E2E (End-To-End)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/bicep-build-to-validate.yml)
  - [ValidateAzCloud (Base validation in Azure Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/base-unit-validate.yml)
  - [ValidateMcCloud (Base validation in Azure China Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/mc-base-unit-validate.yml)
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Module READMEs, Wiki Docs etc.)
- [x] If relevant, created or updated Code Tours [here](https://github.com/Azure/ALZ-Bicep/blob/main/.vscode/tours)

### CODE REVIEW

**Review by sebassem — APPROVED** [review]
LGTM

**Comment by fhpx** [comment]
@oZakari Seems like parameter change for Public IP would require a redeployment of the gateway? I get error code "GatewayIpConfigurationCannotBeChangedOrOverwritten" since Public IP parameter has changed to vnetGatewayConfig1.

**Comment by oZakari** [comment]
Hi @fhpx, just opened a PR (linked above this message) to revert it and also add a parameter where it can be adjusted as needed.

**Pull request merged**
