### PR TITLE
Use latest API versions in all modules

### PR DESCRIPTION
**Pull request by olljanat**
# Overview/Summary
Cherry-picked API version updates from #245 which have not been yet updated since that one was created.

Related to #247

## This PR fixes/adds/changes/removes
One example of this kind of case https://github.com/Azure/bicep/issues/5581#issuecomment-1135935353

Also fixes location in pipelines being consistently taken from key vault/variable instead of hardcoded in places to `eastus`

### Breaking Changes
- Private DNS Zones vNet linking name made unique to ensure can be used multiple times for vNets with the same names:
image

## Testing Evidence
Should be as long as e2e tests pass.

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://github.com/Azure/ALZ-Bicep/wiki/Contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/ALZ-Bicep/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/ALZ-Bicep/issues)
- [ ] *(ALZ Bicep Core Team Only)* Associated it with relevant [ADO Items](https://aka.ms/alz/bicep/backlog)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/ALZ-Bicep/tree/main)
- [ ] Performed testing and provided evidence.
- [ ] Updated tests *(if required)* [Unit](https://github.com/Azure/ALZ-Bicep/blob/main/.github/workflows/bicep-build-to-validate.yml) - [Linting](https://github.com/Azure/ALZ-Bicep/tree/main/.github/workflows) - [E2E (End-To-End)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/bicep-build-to-validate.yml)
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Module READMEs, Wiki Docs etc.)
- [ ] If relevant, created or updated Code Tours [here](https://github.com/Azure/ALZ-Bicep/blob/main/.vscode/tours)

### CODE REVIEW

**Comment by olljanat** [comment]
oh, I totally forgot that those Azure Pipelines are not public.
@jtracey93 can you copy pipeline logs/errors from there to here as record?

**Comment by jtracey93** [comment]
> oh, I totally forgot that those Azure Pipelines are not public. @jtracey93 can you copy pipeline logs/errors from there to here as record?

Hey @olljanat, yup just one of those things im afraid due to the way GitHub handles secrets in PRs from Forks. 

The errors were mainly vwan DNS Zone related, so nothing you did but something your bigger change forced a run of the entire pipeline and highlighted. I have made some changes in your branch to fix and will re-run the tests:

image

**Review by jfaurskov — APPROVED** [review]
LGTM, also tested validate in Mooncake with no issues

**Pull request merged**
