### PR TITLE
Feature addvalidation

### PR DESCRIPTION
**Pull request by MilesCameron-DMs**
# Overview/Summary

Adds validation by adding a validate job for each deploy job. Also adds dependencies for validate to run successfully before deploying.

## This PR fixes/adds/changes/removes

1. Adds validation by passing `whatif` to the deploy jobs
2. Adds dependencies by using `needs` in the GitHub workflow
3. Updated the wiki to add the environment `production`

### Breaking Changes

1. This code requires the environment `production` to be added to the GitHub repo.
   This has been added to the wiki

## Testing Evidence

Limited testing as in the test environment VWAN is not deployed:

image

image

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://github.com/Azure/ALZ-Bicep/wiki/Contributing) and ensured this PR is compliant with the guide
- [x] Ensured the resource API versions in `.bicep` file/s I am adding/editing are using the latest API version possible
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/ALZ-Bicep/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/ALZ-Bicep/issues)
- [ ] *(ALZ Bicep Core Team Only)* Associated it with relevant [ADO Items](https://aka.ms/alz/bicep/backlog)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/ALZ-Bicep/tree/main)
- [x] Performed testing and provided evidence.
- [ ] Updated one or more of the following tests *(if required)*
  - [Unit](https://github.com/Azure/ALZ-Bicep/blob/main/.github/workflows/bicep-build-to-validate.yml)
  - [Linting](https://github.com/Azure/ALZ-Bicep/tree/main/.github/workflows)
  - [E2E (End-To-End)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/bicep-build-to-validate.yml)
  - [ValidateAzCloud (Base validation in Azure Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/base-unit-validate.yml)
  - [ValidateMcCloud (Base validation in Azure China Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/mc-base-unit-validate.yml)
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Module READMEs, Wiki Docs etc.)
- [ ] If relevant, created or updated Code Tours [here](https://github.com/Azure/ALZ-Bicep/blob/main/.vscode/tours)

### CODE REVIEW

**Comment by MilesCameron-DMs** [comment]
@microsoft-github-policy-service agree [company="Airwair International Limited"]

> @MilesCameron-DMs please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement
> ### Contribution License Agreement
> This Contribution License Agreement (**“Agreement”**) is agreed to by the party signing below (**“You”**), and conveys certain license rights to Microsoft Corporation and its affiliates (“Microsoft”) for Your contributions to Microsoft open source projects. This Agreement is effective as of the latest signature date below.
> 
> 1. **Definitions**.
>    **“Code”** means the computer software code, whether in human-readable or machine-executable form,
>    that is delivered by You to Microsoft under this Agreement.
>    **“Project”** means any of the projects owned or managed by Microsoft and offered under a license
>    approved by the Open Source Initiative ([www.opensource.org](http://www.opensource.org)).
>    **“Submit”** is the act of uploading, submitting, transmitting, or distributing code or other content to any
>    Project, including but not limited to communication on electronic mailing lists, source code control
>    systems, and issue tracking systems that are managed by, or on behalf of, the Project for the purpose of
>    discussing and improving that Project, but excluding communication that is conspicuously marked or
>    otherwise designated in writing by You as “Not a Submission.”
>    **“Submission”** means the Code and any other copyrightable material Submitted by You, including any
>    associated comments and documentation.
> 2. **Your Submission**. You must agree to the terms of this Agreement before making a Submission to any
>    Project. This Agreement covers any and all Submissions that You, now or in the future (except as
>    described in Section 4 below), Submit to any Project.
> 3. **Originality of Work**. You represent that each of Your Submissions is entirely Your original work.
>    Should You wish to Submit materials that are not Your original work, You may Submit them separately
>    to the Project if You (a) retain all copyright and license information that was in the materials as You
>    received them, (b) in the description accompanying Your Submission, include the phrase “Submission
>    containing materials of a third party:” followed by the names of the third party and any licenses or other
>    restrictions of which You are aware, and (c) follow any other instructions in the Project’s written
>    guidelines concerning Submissions.
> 4. **Your Employer**. References to “employer” in this Agreement include Your employer or anyone else
>    for whom You are acting in making Your Submission, e.g. as a contractor, vendor, or agent. If Your
>    Submission is made in the course of Your work for an employer or Your employer has intellectual
>    property rights in Your Submission by contract or applicable law, You must secure permission from Your
>    employer to make the Submission before signing this Agreement. In that case, the term “You” in this
>    Agreement will refer to You and the employer collectively. If You change employers in the future and
>    desire to Submit additional Submissions for the new employer, then You agree to sign a new Agreement
>    and secure permission from the new employer before Submitting those Submissions.
> 5. **Licenses**.
> 
> * **Copyright License**. You grant Microsoft, and those who receive the Submission directly or
>   indirectly from Microsoft, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable license in the
>   Submission to reproduce, prepare derivative works of, publicly display, publicly perform, and distribute
>   the Submission and such derivative works, and to sublicense any or all of the foregoing rights to third
>   parties.
> * **Patent License**. You grant Microsoft, and those who receive the Submission directly or
>   indirectly from Microsoft, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable license under
>   Your patent claims that are necessarily infringed by the Submission or the combination of the
>   Submission with the Project to which it was Submitted to make, have made, use, offer to sell, sell and
>   import or otherwise dispose of the Submission alone or with the Project.
> * **Other Rights Reserved**. Each party reserves all rights not expressly granted in this Agreement.
>   No additional licenses or rights whatsoever (including, without limitation, any implied licenses) are
>   granted by implication, exhaustion, estoppel or otherwise.
> 
> 6. **Representations and Warranties**. You represent that You are legally entitled to grant the above
>    licenses. You represent that each of Your Submissions is entirely Your original work (except as You may
>    have disclosed under Section 3). You represent that You have secured permission from Your employer to
>    make the Submission in cases where Your Submission is made in the course of Your work for Your
>    employer or Your employer has intellectual property rights in Your Submission by contract or applicable
>    law. If You are signing this Agreement on behalf of Your employer, You represent and warrant that You
>    have the necessary authority to bind the listed employer to the obligations contained in this Agreement.
>    You are not expected to provide support for Your Submission, unless You choose to do so. UNLESS
>    REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING, AND EXCEPT FOR THE WARRANTIES
>    EXPRESSLY STATED IN SECTIONS 3, 4, AND 6, THE SUBMISSION PROVIDED UNDER THIS AGREEMENT IS
>    PROVIDED WITHOUT WARRANTY OF ANY KIND, INCLUDING, BUT NOT LIMITED TO, ANY WARRANTY OF
>    NONINFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
> 7. **Notice to Microsoft**. You agree to notify Microsoft in writing of any facts or circumstances of which
>    You later become aware that would make Your representations in this Agreement inaccurate in any
>    respect.
> 8. **Information about Submissions**. You agree that contributions to Projects and information about
>    contributions may be maintained indefinitely and disclosed publicly, including Your name and other
>    information that You submit with Your Submission.
> 9. **Governing Law/Jurisdiction**. This Agreement is governed by the laws of the State of Washington, and
>    the parties consent to exclusive jurisdiction and venue in the federal courts sitting in King County,
>    Washington, unless no federal subject matter jurisdiction exists, in which case the parties consent to
>    exclusive jurisdiction and venue in the Superior Court of King County, Washington. The parties waive all
>    defenses of lack of personal jurisdiction and forum non-conveniens.
> 10. **Entire Agreement/Assignment**. This Agreement is the entire agreement between the parties, and
>     supersedes any and all prior agreements, understandings or communications, written or oral, between
>     the parties relating to the subject matter hereof. This Agreement may be assigned by Microsoft.

**Comment by MilesCameron-DMs** [comment]
@microsoft-github-policy-service agree company="Airwair International Ltd"

**Comment by picccard** [comment]
Great to have some more validation before deployment! 👍 

The PR itself adds an approval gate, so maybe there is not need for the requirement to use environments in github. 

The pipelines should limit the number of duplicated steps, it would be simpler to define each step only one time and trigger pipeline runs on both pull request into main and push into main. Some of the steps could have if-expressions to only run in certain scenarios:
- The last step, Deploy X module, could have an expression so it only runs actual deployment on push into main, not pull requests.
- And a step named "Push Whatif Output to PR" that only runs on pull requests.


Also I had a look at the updates to the Deploy-ALZ*.ps1 scripts. Just using the -WhatIf flag only prints the pending changes to the host/console, without any way to store the result in a variable. If the result of a WhatIf should be published as text into the PR; have a look at Get-AzManagementGroupDeploymentWhatIfResult, etc.


<details><summary>Code examples</summary>

e.g. `Deploy-ALZSubscriptionPlacement.ps1` could return the WhatIf-results as text
```
if ($WhatIf) {
  return (Get-AzManagementGroupDeploymentWhatIfResult @inputObject | Out-String)
}

New-AzManagementGroupDeployment @inputObject
```

e.g `alz-bicep-3.yml` could use this results in a message on the PullRequest, as long as the env-var to enable this feature is true (allows others easier to enable/disable this)
```yml
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

env:
  ENV_FILE: ".env"
  WHATIF_TO_PR: false

permissions:
    id-token: write
    contents: read
    pull-requests: write

...

      - name: What-If
        id: whatif
        if: github.event_name == 'pull_request'
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $whatif = .\pipeline-scripts\Deploy-ALZSubscriptionPlacement.ps1 -WhatIf $true
            $whatif | Out-String
            -join (1..15 | ForEach {[char]((48..57)+(65..90)+(97..122) | Get-Random)}) | Set-Variable -Name EOF
            "WHATIF<<$EOF" >> $env:GITHUB_OUTPUT
            $whatif >> $env:GITHUB_OUTPUT
            "$EOF" >> $env:GITHUB_OUTPUT
          azPSVersion: "latest"

      - name: Push Whatif Output to PR
        if: github.event_name == 'pull_request' && env.WHATIF_TO_PR == true
        uses: actions/github-script@v6
        env:
          WHATIF: "${{ steps.whatif.outputs.WHATIF }}"
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              const output = `#### Deployment WhatIf 📖\`${{ steps.whatif.outcome }}\`

              <details><summary>Show Plan</summary>

              \`\`\`text\n
              ${process.env.WHATIF}
              \`\`\`

              </details>

              *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              })

      - name: Deploy Subscription Placement
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: azure/powershell@v1
        with:
          inlineScript: |
            .\pipeline-scripts\Deploy-ALZSubscriptionPlacement.ps1
          azPSVersion: "latest"
```

</details>

**Comment by MilesCameron-DMs** [comment]
@picccard Thanks for the feedback, i was working on using the output - perhaps for the step summary. One change at a time i guess.

Agree about the duplication of code and i changed my PR to minimise this.

Also, the environment approval runs before the deployment job runs, straight after the validation - unlike the approval gate via the branch protection which runs when there is a PR. Try it yourself and you will see it flows better. Take  your point about changing the triggers, i have similar workflows for some of our repo's.

I am just trying to get validation in to the workflow with what we have at the moment and we can work on the rest next?

**Comment by oZakari** [comment]
Thanks @MilesCameron-DMs! I like the idea of using environments, especially if we end up incorporating the option to deploy to `[canary environments](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/testing-approach)` within the Accelerator. 

We were also thinking about adding the output to a comment as @picccard suggested as well. I will play around with this a bit this week and I may end up opening a PR with some potential changes as a heads up.

**Comment by oZakari** [comment]
@MilesCameron-DMs I just opened a PR against your branch if you wouldn't mind taking a look. I am holding off on adding on adding the comments to outputs as the approach I want to go with requires some modification of the ALZ Powershell module.

**Comment by MilesCameron-DMs** [comment]
@oZakari thanks for that. I have reviewed and merged. Much neater solution 👍

**Comment by oZakari** [comment]
> @oZakari thanks for that. I have reviewed and merged. Much neater solution 👍

Thank you, @MilesCameron-DMs! I resubmitted a PR as I realized I originally requested it against your main branch and not your feature branch.

**Review by oZakari — APPROVED** [review]

**Pull request merged**
