### PR TITLE
Option for subnet delegations

### PR DESCRIPTION
**Pull request by picccard**
# Overview/Summary

Delegating a subnet to an azure service is possible in terraform, but not yet possible in the bicep version of ALZ. 
The feature is not well documented though: [https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/711](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/711)

## This PR fixes/adds/changes/removes

1. Adds support for optional delegating a subnet to an single azure service
1.1 Subnets that should not have delegations can skip/ignore the use of this property
1.2 The vnet resource api accepts the delegation object to be a list, but my attempt to delegate for two services failed. I've never successfully delegated a subnet to two services, that might cause conflicts if both azure services deploy stuff into the subnet on the same IP(?)

### Breaking Changes

None

## Testing Evidence
-WhatIf deployment of two new subnets with delegation:
image

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://github.com/Azure/ALZ-Bicep/wiki/Contributing) and ensured this PR is compliant with the guide
- [x] Ensured the resource API versions in `.bicep` file/s I am adding/editing are using the latest API version possible
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/ALZ-Bicep/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/ALZ-Bicep/issues)
- [ ] *(ALZ Bicep Core Team Only)* Associated it with relevant [ADO Items](https://aka.ms/alz/bicep/backlog)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/ALZ-Bicep/tree/main)
- [x] Performed testing and provided evidence.
- [ ] Updated one or more of the following tests *(if required)*
  - [Unit](https://github.com/Azure/ALZ-Bicep/blob/main/.github/workflows/bicep-build-to-validate.yml)
  - [Linting](https://github.com/Azure/ALZ-Bicep/tree/main/.github/workflows)
  - [E2E (End-To-End)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/bicep-build-to-validate.yml)
  - [ValidateAzCloud (Base validation in Azure Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/base-unit-validate.yml)
  - [ValidateMcCloud (Base validation in Azure China Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/mc-base-unit-validate.yml)
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Module READMEs, Wiki Docs etc.)
- [ ] If relevant, created or updated Code Tours [here](https://github.com/Azure/ALZ-Bicep/blob/main/.vscode/tours)

### CODE REVIEW

**Review by jtracey93 — CHANGES_REQUESTED** [review]
Thanks @piccard, please remove the Private DNS Resolver additions here and just leave the delegation pieces

**Comment by picccard** [comment]
Ok, removed the new subnets and left only the functionality to delegate subnets.

There is not any doc explaining how-to delegate subnets yet, but I don't see any good place to put it.

**Comment by jtracey93** [comment]
@piccard could you resolve the test failures please 👍

**Review by jtracey93 — APPROVED** [review]

**Pull request merged**
