### PR TITLE
chore: bicepconfig.json linter update

### PR DESCRIPTION
**Pull request by DaFitRobsta**
# Overview/Summary

As part of Bicep release v0.10.13 new linter rules have been added. [Azure/bicep: Bicep is a declarative language for describing and deploying Azure resources (github.com)](https://github.com/Azure/bicep/releases/tag/v0.10.13)

We need to update the bicepconfig.json and Contribution Guide Wiki example of the bicepconfig.json file in ALZ-Bicep to ensure our tests utilize these new rules.

## This PR fixes/adds/changes/removes

1. Update Linter Rules to Latest Available in Bicep v0.10.13 for all bicepconfig.json files under /infra-as-code/bicep
```bicep
        "artifacts-parameters":{
          "level": "error"
        },
        "no-unused-existing-resources":{
          "level": "error"
        },
        "prefer-unquoted-property-names":{
          "level": "error"
        },
        "secure-params-in-nested-deploy":{
          "level": "error"
        },
        "secure-secrets-in-params":{
          "level": "error"
        },
        "use-recent-api-versions":{
          "level": "error"
        },
        "use-resource-id-functions":{
          "level": "error"
        },
        "use-stable-resource-identifiers":{
          "level": "error"
        }
```
2. After updating all linter rules, there were a number of bicep files that failed to compile. Most of them needed their resource provider API version updated to the latest.

### Breaking Changes

None

## Testing Evidence

Automated testing will suffice.

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://github.com/Azure/ALZ-Bicep/wiki/Contributing) and ensured this PR is compliant with the guide
- [ ] Ensured the resource API versions in `.bicep` file/s I am adding/editing are using the latest API version possible
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/ALZ-Bicep/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/ALZ-Bicep/issues)
- [x] *(ALZ Bicep Core Team Only)* Associated it with relevant [ADO Items](https://aka.ms/alz/bicep/backlog)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/ALZ-Bicep/tree/main)
- [x] Performed testing and provided evidence.
- [ ] Updated one or more of the following tests *(if required)*
  - [Unit](https://github.com/Azure/ALZ-Bicep/blob/main/.github/workflows/bicep-build-to-validate.yml)
  - [Linting](https://github.com/Azure/ALZ-Bicep/tree/main/.github/workflows)
  - [E2E (End-To-End)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/bicep-build-to-validate.yml)
  - [ValidateAzCloud (Base validation in Azure Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/base-unit-validate.yml)
  - [ValidateMcCloud (Base validation in Azure China Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/mc-base-unit-validate.yml)
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Module READMEs, Wiki Docs etc.)
- [ ] If relevant, created or updated Code Tours [here](https://github.com/Azure/ALZ-Bicep/blob/main/.vscode/tours)

### CODE REVIEW

**Review by jtracey93 — DISMISSED** [review]
Looks great, will merge once checks pass.

Thanks

**Review by jtracey93 — CHANGES_REQUESTED** [review]
Hey @DaFitRobsta,

So, it did look good but the validation tests picked up an error based on the new linting rules for management groups at least which I think is a bicep bug so have raised here: https://github.com/Azure/bicep/issues/8410

This then got me thinking why did ADO find it but not the GitHub Action. Investigation shows that the bicep version on the GitHub Action runner was 0.9.1 and not the latest. So have added some steps to the workflow `.github/workflows/bicep-build-to-validate.yml` in your branch (so just do a git pull to update your local clone of it) to now include a step to tell us the version and also install the latest version of bicep so we dont get hit by this again 👍

Now for you to investigate and work through these linter issues being highlighted as well as the upstream issue I created (I suspect we will get an answer from PG today/tomorrow - hopefully)

Any questions, ping me

**Comment by DaFitRobsta** [comment]
Hello @jtracey93,
I updated the CARML container registry bicep based on the linter failed check for using the latest API version. Also updated my local Bicep to the latest.
Thank you!

**Comment by jtracey93** [comment]
> Hello @jtracey93,
> 
> I updated the CARML container registry bicep based on the linter failed check for using the latest API version. Also updated my local Bicep to the latest.
> 
> Thank you!

Onto the next failure. Might be worth changing the action to continue on error instead of throw straight out. And capture all failure in a variable and then display them all at the end. 

Might make the process a bit better.

**Comment by DaFitRobsta** [comment]
Hey @jtracey93,
The pipeline ran successfully. Please review and let me know if you have any questions.
Thank you

**Comment by jtracey93** [comment]
E2Es failed due to FW and VWAN trying to be deployed at same time due to condition check error on ADO E2E (bug has been logged for this to be fixed)

Will merge PR

**Pull request merged**
