### PR TITLE
Add NSG to AzureBastionSubnet - Fixing #240

### LINKED ISSUE #240: 💡 Feature Request - Add NSGs to AzureBastionSubnet
## Describe the solution you'd like

Currently hub network modules deploy bastion subnet `AzureBastionSubnet` without NSGs. The `AzureBastionSubnet` subnet supports NSGs and it is a Well-Architected Framework (WAF) recommendation to deploy all subnets with NSGs. No specific exclusion applies for `AzureBastionSubnet`.

Requirements for Bastion NSG is here: https://docs.microsoft.com/azure/bastion/bastion-nsg#nsg

See:

- https://docs.microsoft.com/azure/architecture/framework/security/design-network-segmentation
- https://docs.microsoft.com/azure/security/fundamentals/network-best-practices#logically-segment-subnets

## Additional context

This is reported by PSRule for Azure: https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.VNET.UseNSGs/

Related to #206

### PR DESCRIPTION
**Pull request by jtracey93**
# Overview/Summary

This PR adds an NSG to the AzureBastionSubnet 

## This PR fixes/adds/changes/removes

1. Fixes #240 by adding NSG to AzureBastionSubnet

### Breaking Changes

None

## Testing Evidence

Tested in my own environment and deployed successfully.

PR Tests will confirm also

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://github.com/Azure/ALZ-Bicep/wiki/Contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/ALZ-Bicep/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/ALZ-Bicep/issues)
- [ ] *(ALZ Bicep Core Team Only)* Associated it with relevant [ADO Items](https://aka.ms/alz/bicep/backlog)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/ALZ-Bicep/tree/main)
- [x] Performed testing and provided evidence.
- [ ] Updated one or more of the following tests *(if required)*
  - [Unit](https://github.com/Azure/ALZ-Bicep/blob/main/.github/workflows/bicep-build-to-validate.yml)
  - [Linting](https://github.com/Azure/ALZ-Bicep/tree/main/.github/workflows)
  - [E2E (End-To-End)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/bicep-build-to-validate.yml)
  - [ValidateAzCloud (Base validation in Azure Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/base-unit-validate.yml)
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Module READMEs, Wiki Docs etc.)
- [ ] If relevant, created or updated Code Tours [here](https://github.com/Azure/ALZ-Bicep/blob/main/.vscode/tours)

### CODE REVIEW

**Comment by jtracey93** [comment]
Markdown link check failure is a false positive.

**Review by jfaurskov — APPROVED** [review]
LGTM

**Pull request merged**
