### PR TITLE
Corrected some typo's, camelCasing inconsistency fixes and added defaults

### PR DESCRIPTION
**Pull request by johnlokerse**
## This PR fixes/adds/changes/removes

1. Corrected typo's
2. Fixes to some camelCasing inconsistencies
3. Added defaults to the description

### Breaking Changes

1. If someone copy and paste this template it will break on `parDnsServerIPs` when using a parameter file with the "old" parameter name.

#### JT Notes

- `parDNSServerIPArray` to `parDnsServerIPs`
- `parSpoketoHubRouteTableName` to `parSpokeToHubRouteTableName`

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://github.com/Azure/ALZ-Bicep/wiki/Contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/ALZ-Bicep/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/ALZ-Bicep/issues)
- [ ] *(ALZ Bicep Core Team Only)* Associated it with relevant [ADO Items](https://aka.ms/alz/bicep/backlog)
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/ALZ-Bicep/tree/main)
- [ ] Performed testing and provided evidence.
- [ ] Updated tests *(if required)* [Unit](https://github.com/Azure/ALZ-Bicep/blob/main/.github/workflows/bicep-build-to-validate.yml) - [Linting](https://github.com/Azure/ALZ-Bicep/tree/main/.github/workflows) - [E2E (End-To-End)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/bicep-build-to-validate.yml)
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Module READMEs, Wiki Docs etc.)
- [ ] If relevant, created or updated Code Tours [here](https://github.com/Azure/ALZ-Bicep/blob/main/.vscode/tours)

### CODE REVIEW

**Comment by johnlokerse** [comment]
@jtracey93 For some reason I can't set a comment, but in the README in the spokeNetworking folder, it says that the spokeNetworking.bicep creates a **subnet**. This is not what the template does. Is this an error or shall I add the possibility to add one or more subnets?

**Comment by jtracey93** [comment]
> @jtracey93 For some reason I can't set a comment, but in the README in the spokeNetworking folder, it says that the spokeNetworking.bicep creates a **subnet**. This is not what the template does. Is this an error or shall I add the possibility to add one or more subnets?

Hey @johnlokerse, this is indeed and error. We do not create subnets today as this would mean a complex object input parameter today which we cannot validate. 

So please remove from the docs 👍

**Comment by johnlokerse** [comment]
@jtracey93 Done!

**Review by jtracey93 — APPROVED** [review]
LGTM 🚢

**Pull request merged**
