### PR TITLE
fix: Private DNS Zones Bug (#695)

### LINKED ISSUE #695: Bicep Accelerator Private DNS Zone for "privatelink.*.backup.windowsazure.com" Incorrectly lists uksouth
### What happened? Provide a clear and concise description of the bug, including deployment details.

When using the Accelerator, I used the location default as uksouth

When referencing the file: config\custom-parameters\hubNetworking.parameters.all.json

for the Private DNS Zone "privatelink.*.backup.windowsazure.com", it uses the region name uksouth rather than the geo code uks

e.g it displays:         "privatelink.uksouth.backup.windowsazure.com"  

rather than 

        "privatelink.uks.backup.windowsazure.com",

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### What was the expected outcome?

_No response_

### Relevant log output

_No response_

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jtracey93**
# Overview/Summary

This PR Fixes the  Private DNS Zones Bug #695 

## Related Issues/Work Items

Fixes #695 

## This PR fixes/adds/changes/removes

- Fixes #695 

### Breaking Changes

A number of breaking changes

<details>
  <summary>Draft Release Notes</summary>

The local private DNS zones modules (`privateDnsZones.bicep`) has been replaced in the networking related modules in this repo with the AVM Pattern module of [`avm/ptn/network/private-link-private-dns-zones`](https://github.com/Azure/bicep-registry-modules/tree/main/avm/ptn/network/private-link-private-dns-zones) to resolve bug #695.

This has meant some breaking changes to each of the networking modules that are detailed below.

#### `privateDnsZones.bicep`

- This module has been removed as of `v0.20.0` and replaced with the AVM Pattern Module of [`avm/ptn/network/private-link-private-dns-zones`](https://github.com/Azure/bicep-registry-modules/tree/main/avm/ptn/network/private-link-private-dns-zones). Please use this module going forward.

#### `hubNetworking.bicep` & `hubNetworking-multiRegion.bicep`

- `parPrivateDnsZones` default value changed to an empty array (`[]`)
    - Only enter values in here if you want to override the defaults in the underlying AVM pattern module. See: https://github.com/Azure/bicep-registry-modules/tree/main/avm/ptn/network/private-link-private-dns-zones#parameter-privatelinkprivatednszones
- `parPrivateDnsZoneAutoMergeAzureBackupZone` removed from module
- `parVirtualNetworkResourceIdsToLinkTo` added to module, you can prefer to use this parameter instead of `parVirtualNetworkIdToLink` & `parVirtualNetworkIdToLinkFailover` if you wish (they are automatically all merged together by the module anyway)
- The value returned in `outPrivateDnsZones` has changed

**From:**

```
[
  {
    "name": "privatelink.api.azureml.ms",
    "id": "/subscriptions/<subID>/resourceGroups/<rgID>/providers/Microsoft.Network/privateDnsZones/privatelink.api.azureml.ms"
  },
  {
    "name": "privatelink.notebooks.azure.net",
    "id": "subscriptions/<subID>/resourceGroups/<rgID>/providers/Microsoft.Network/privateDnsZones/privatelink.notebooks.azure.net"
  },
  …
]
```

**To:**
```
[
  {
    "pdnsZoneName": "privatelink.api.azureml.ms",
    "virtualNetworkResourceIdsToLinkTo": [
      "/subscriptions/<subID>/resourceGroups/<rgID>/providers/Microsoft.Network/virtualNetworks/alz-hub-uksouth"
    ]
  },
  {
    "pdnsZoneName": "privatelink.notebooks.azure.net",
    "virtualNetworkResourceIdsToLinkTo": [
      "/subscriptions/<subID>/resourceGroups/<rgID>/providers/Microsoft.Network/virtualNetworks/alz-hub-uksouth"
    ]
  },
  …
]
```

#### `vwanConnectivity.bicep`

- `parPrivateDnsZones` default value changed to an empty array (`[]`)
    - Only enter values in here if you want to override the defaults in the underlying AVM pattern module. See: https://github.com/Azure/bicep-registry-modules/tree/main/avm/ptn/network/private-link-private-dns-zones#parameter-privatelinkprivatednszones
- `parVirtualNetworkIdToLink` & `parVirtualNetworkIdToLinkFailover` removed from module and replaced with `parVirtualNetworkResourceIdsToLinkTo`
- The value returned in `outPrivateDnsZones` has changed

**From:**

```
[
  {
    "name": "privatelink.api.azureml.ms",
    "id": "/subscriptions/<subID>/resourceGroups/<rgID>/providers/Microsoft.Network/privateDnsZones/privatelink.api.azureml.ms"
  },
  {
    "name": "privatelink.notebooks.azure.net",
    "id": "subscriptions/<subID>/resourceGroups/<rgID>/providers/Microsoft.Network/privateDnsZones/privatelink.notebooks.azure.net"
  },
  …
]
```

**To:**
```
[
  {
    "pdnsZoneName": "privatelink.api.azureml.ms",
    "virtualNetworkResourceIdsToLinkTo": [
      "/subscriptions/<subID>/resourceGroups/<rgID>/providers/Microsoft.Network/virtualNetworks/alz-hub-uksouth"
    ]
  },
  {
    "pdnsZoneName": "privatelink.notebooks.azure.net",
    "virtualNetworkResourceIdsToLinkTo": [
      "/subscriptions/<subID>/resourceGroups/<rgID>/providers/Microsoft.Network/virtualNetworks/alz-hub-uksouth"
    ]
  },
  …
]
```

</details>

## Testing Evidence

Screenshot 2024-11-01 162738

Screenshot 2024-11-01 162804

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://github.com/Azure/ALZ-Bicep/wiki/Contributing) and ensured this PR is compliant with the guide
- [x] Ensured the resource API versions in `.bicep` file/s I am adding/editing are using the latest API version possible
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/ALZ-Bicep/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/ALZ-Bicep/issues)
- [x] *(ALZ Bicep Core Team Only)* Associated it with relevant [ADO Items](https://aka.ms/alz/bicep/backlog)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/ALZ-Bicep/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated one or more of the following tests *(if required)*
  - [Unit](https://github.com/Azure/ALZ-Bicep/blob/main/.github/workflows/bicep-build-to-validate.yml)
  - [Linting](https://github.com/Azure/ALZ-Bicep/tree/main/.github/workflows)
  - [E2E (End-To-End)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/bicep-build-to-validate.yml)
  - [ValidateAzCloud (Base validation in Azure Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/base-unit-validate.yml)
  - [ValidateMcCloud (Base validation in Azure China Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/mc-base-unit-validate.yml)
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Module READMEs, Wiki Docs etc.)
- [x] If relevant, created or updated Code Tours [here](https://github.com/Azure/ALZ-Bicep/blob/main/.vscode/tours)

### CODE REVIEW

**Comment by jtracey93** [comment]
@oZakari & @sebassem would appreciate a review here. Especially around the accelerator and multi region angle

**Review by sebassem — APPROVED** [review]
LGTM , should we add an example specifically for multi-region to make it clear how to add region-aware private dns zones ?

**Comment by jtracey93** [comment]
> LGTM , should we add an example specifically for multi-region to make it clear how to add region-aware private dns zones ?

@sebassem is this not already in the hub spoke multi-region, where i call the DNS zones twice with a different location.

I actually plan on adding the feature to my AVM modules to make it a simpler toggle

**Review by oZakari — COMMENTED** [review]
LGTM and you're good with the multi-region adjustments you made from my point of view.

I also tested the Accelerator, and all looks good. Thanks much!

**Review by oZakari — APPROVED** [review]

**Pull request merged**
