### PR TITLE
US 31189 - Add BICEPPARAM files to modules

### PR DESCRIPTION
**Pull request by appli3d**
# Overview/Summary

PR to add BICEPPARAM files in co-existence with JSON parameter files. Also added Code snippets into Markdowns.

[AB#31189](https://dev.azure.com/CSUSolEng/2a9d5a5a-8998-4ad0-81c8-ef3045e4da97/_workitems/edit/31189)

## This PR fixes/adds/changes/removes

1. Added BICEPPARAM files into the same folder as the JSON parameters for each respective module

### Breaking Changes

1. N/A

## Testing Evidence

image

## As part of this Pull Request I have

- [X] Read the [Contribution Guide](https://github.com/Azure/ALZ-Bicep/wiki/Contributing) and ensured this PR is compliant with the guide
- [X] Ensured the resource API versions in `.bicep` file/s I am adding/editing are using the latest API version possible
- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/ALZ-Bicep/pulls)
- [X] Associated it with relevant [GitHub Issues](https://github.com/Azure/ALZ-Bicep/issues)
- [X] *(ALZ Bicep Core Team Only)* Associated it with relevant [ADO Items](https://aka.ms/alz/bicep/backlog)
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/ALZ-Bicep/tree/main)
- [X] Performed testing and provided evidence.
- [X] Updated one or more of the following tests *(if required)*
  - [Unit](https://github.com/Azure/ALZ-Bicep/blob/main/.github/workflows/bicep-build-to-validate.yml)
  - [Linting](https://github.com/Azure/ALZ-Bicep/tree/main/.github/workflows)
  - [E2E (End-To-End)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/bicep-build-to-validate.yml)
  - [ValidateAzCloud (Base validation in Azure Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/base-unit-validate.yml)
  - [ValidateMcCloud (Base validation in Azure China Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/mc-base-unit-validate.yml)
- [X] Updated relevant and associated documentation (e.g. Contribution Guide, Module READMEs, Wiki Docs etc.)
- [X] If relevant, created or updated Code Tours [here](https://github.com/Azure/ALZ-Bicep/blob/main/.vscode/tours)

### CODE REVIEW

**Comment by oZakari** [comment]
Thanks James! I'll go over this tomorrow morning.

**Comment by picccard** [comment]
Wow great stuff @appli3d !

Have you done any testing with bicepparam files located in the config/custom-parameters folder as per the accelerator folder-structure?

Any bicepparam there would have to start with using '../upstream-versions/v0.16.6/infra-as-code/...'
So how would upgrading to any newer release be handled? All bicepparams would be manually updated or could the env:UPSTREAMVERSION be used there?

**Comment by oZakari** [comment]
Looking through some of the tests to make sure nothing is missed but so far looks good. @appli3d

**Comment by oZakari** [comment]
Hi @picccard! We are looking in transitioning the Accelerator to the bicepparam files in the next couple of months. You should be able to transition your existing json parameter files within the Accelerator, but would have to adjust the [using statement](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/bicep-using) from the ones included in this PR.

**Comment by oZakari** [comment]
Holding off on merging this until we sort the Accelerator out.

**Comment by oZakari** [comment]
Holding off on Bicep params until we get updates from PG on whether they decide to remove the using statements.

**Pull request closed without merging**
