### PR TITLE
Documenting minimal network deployment, and fix about modified Modules

### PR DESCRIPTION
**Pull request by marcosgm**
# Overview/Summary
Added an example of parametrization to reduce the infra costs by disabling network security elements
It also fixes the example of customizing logging.bicep but refers to the wrong PS1 file

## This PR fixes/adds/changes/removes
Minimalistic network deployment that reduces the cost to almost zero, referred in the sectiosn where we review the parameter files within config/custom-parameters
Proper reference to pipeline-scripts\Deploy-ALZLoggingAndSentinel.ps1

### Breaking Changes

No code changes

## Testing Evidence

No code changes

## As part of this Pull Request I have

- [x ] Read the [Contribution Guide](https://github.com/Azure/ALZ-Bicep/wiki/Contributing) and ensured this PR is compliant with the guide
- [ ] Ensured the resource API versions in `.bicep` file/s I am adding/editing are using the latest API version possible
- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/ALZ-Bicep/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/ALZ-Bicep/issues)
- [ ] *(ALZ Bicep Core Team Only)* Associated it with relevant [ADO Items](https://aka.ms/alz/bicep/backlog)
- [x ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/ALZ-Bicep/tree/main)
- [ ] Performed testing and provided evidence.
- [ ] Updated one or more of the following tests *(if required)*
  - [Unit](https://github.com/Azure/ALZ-Bicep/blob/main/.github/workflows/bicep-build-to-validate.yml)
  - [Linting](https://github.com/Azure/ALZ-Bicep/tree/main/.github/workflows)
  - [E2E (End-To-End)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/bicep-build-to-validate.yml)
  - [ValidateAzCloud (Base validation in Azure Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/base-unit-validate.yml)
  - [ValidateMcCloud (Base validation in Azure China Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/mc-base-unit-validate.yml)
- [ x] Updated relevant and associated documentation (e.g. Contribution Guide, Module READMEs, Wiki Docs etc.)
- [ ] If relevant, created or updated Code Tours [here](https://github.com/Azure/ALZ-Bicep/blob/main/.vscode/tours)

### CODE REVIEW

**Comment by marcosgm** [comment]
@microsoft-github-policy-service agree

**Review by oZakari — APPROVED** [review]
Thanks @marcosgm, looks good from a content perspective, could you just take a look at the PR builds below and fix the lint errors?

**Review by oZakari — CHANGES_REQUESTED** [review]
Thanks @marcosgm, looks good from a content perspective! There are just a few lint errors and then we should be good to go.

**Review by oZakari — APPROVED** [review]
LGTM, thanks @marcosgm!

**Pull request merged**
