### PR TITLE
Standardize on parLocation for specifying Azure regions.

### PR DESCRIPTION
**Pull request by rjygraham**
Renames all instances of `parRegion` to `parLocation` in code and documentation to be in alignment with the vast majority of ALZ-Bicep modules and ARM/TF ESLZ.

## This PR fixes/adds/changes/removes

1. All occurrences of `parRegion` renamed to `parLocation`

### Breaking Changes

1. Existing clones of the ALZ-Bicep repository will need to update `parRegion` to `parLocation` for deployments of `hubNetworking` and `spokeNetworking` module parameter files.

## Testing Evidence

*hubNetworking*
image

*spokeNetworking*
image

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/ALZ-Bicep/pulls)
- [ ] Associated it with relevant [ADO items](https://dev.azure.com/unifiedactiontracker/Solution%20Engineering/_backlogs/backlog/Azure%20Landing%20Zone%20Bicep/Backlog%20Bugs%20Feedback)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/ALZ-Bicep/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.

### CODE REVIEW

**Review by jtracey93 — CHANGES_REQUESTED** [review]
Thanks @rjygraham nice work. I think we need to also update the logging and resource group module as they don't use the new standard of parLocation here. They use some thing like parResourceGroupLocation etc. let's make them all the same 👍

Also in the contributing wiki page can we add a new "Standardised Common Parameter" section for things like this and tags etc.

**Comment by jtracey93** [comment]
Linking to ADO item: https://dev.azure.com/unifiedactiontracker/Solution%20Engineering/_workitems/edit/100633

**Comment by rjygraham** [comment]
@jtracey93  - due to disparity in China region availability for Log Analytics and Automation Accounts, I believe we'll need to leave the logging module with separate parameters for now: `parAutomationAccountRegion` and `parLogAnalyticsWorkspaceLocation` instead of a single `parLocation` parameter.

**Comment by jtracey93** [comment]
@rjygraham is this good to review again? 

With the changes we spoke about yesterday?

**Pull request merged**
