### PR TITLE
Azure Firewall custom DNS server

### PR DESCRIPTION
**Pull request by juang903**
# Overview/Summary

Adds support for configuring the custom DNS server used in Azure Firewall

## This PR fixes/adds/changes/removes

1. Adds the options to configure custom DNS server in Azure Firewall
2. Changes markdown files as appropriate

## Testing Evidence

Entered an array of IPs and verified they were set in Azure Firewall DNS. Entered an empty array and verified that Default (azure provided) DNS is selected. No errors on deployment.

### CODE REVIEW

**Review by jtracey93 — CHANGES_REQUESTED** [review]
Thanks @juang903, could you also add it to the VWAN Module? https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/modules/vwanConnectivity

**Review by jtracey93 — CHANGES_REQUESTED** [review]
Thanks again @juang903 could you also add the new parameter with its default value to the `parameters.all.json` files for each module respectively as well please? 👍

**Comment by juang903** [comment]
@jtracey93 Thanks, I added the params. I also added params for my last bastion PR since those weren't added previously, hope that's ok.

**Comment by jtracey93** [comment]
Thanks @juang903, all good. Can you please fix the linting errors here: https://github.com/Azure/ALZ-Bicep/actions/runs/5941466329/job/16169596767?pr=615

Installing EditorConfig VSCode extension should help you here

**Comment by jtracey93** [comment]
Hi @juang903,

Are you able to resolve the linting errors by installing editorConfig in VSCode and formatting the edited files youve touched?

**Comment by juang903** [comment]
Hi @jtracey93 
I think the linting errors are resolved now.

**Review by jtracey93 — APPROVED** [review]
LGTM

**Pull request merged**
