### PR TITLE
Example parameter files updates in content and path

### PR DESCRIPTION
**Pull request by danycontre**
# Overview/Summary

-- Created parameters folder for each module
-- Moved example parameters files into the parameters folder
-- Created a minimum parameters version of the parameter example files
-- Updated test definition file with the new path to the parameter files (added /parameters/ folder to the path)

## This PR fixes/adds/changes/removes

1. Created parameters folder for each module
2. Moved example parameters files into the parameters folder
3. Created a minimum parameters version of the parameter example files
4. Updated test definition file with the new path to the parameter files (added /parameters/ folder to the path)

### Breaking Changes

None

## Testing Evidence

Replace this with any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

## As part of this Pull Request I have

- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/ALZ-Bicep/pulls)
- [X] Associated it with relevant [ADO items][(https://dev.azure.com/unifiedactiontracker/Solution%20Engineering/_backlogs/backlog/Azure%20Landing%20Zone%20Bicep/Backlog%20Bugs%20Feedback)](https://dev.azure.com/unifiedactiontracker/Solution%20Engineering/_boards/board/t/Azure%20Landing%20Zone%20Bicep/Backlog%20Bugs%20Feedback/?workitem=100645)
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/ALZ-Bicep/tree/main)
- [ ] Performed testing and provided evidence.
- [ ] Updated relevant and associated documentation.

### CODE REVIEW

**Review by jfaurskov — CHANGES_REQUESTED** [review]
Where existing parameter files has been moved to /parameters subfolder, please ensure that ./tests/pipelines/bicep-build-to-validate.yml parameter file references are updated accordingly and run success E2E test before merging.

**Review by jfaurskov — APPROVED** [review]
Missed the last file. LGTM

**Comment by jtracey93** [comment]
@msftbot require at least 2 approvals for this PR

**Comment by jtracey93** [comment]
forget everything I just told you

**Comment by jtracey93** [comment]
@msftbot forget everything I just told you

**Comment by jtracey93** [comment]
@msftbot require at least 2 approvals from maintainers for this PR

also @jtracey93 must review

**Comment by jtracey93** [comment]
@msftbot forget everything I just told you

**Comment by jtracey93** [comment]
@msftbot require approvals from both @jtracey93 & @jfaurskov on this PR

**Comment by jtracey93** [comment]
> This pull request has been automatically marked as stale because it has been marked as requiring author feedback but has not had any activity for **7 days**. It will be closed if no further activity occurs **within 7 days of this comment**.

Not stale. Under review still 👍

**Review by jtracey93 — CHANGES_REQUESTED** [review]
Thanks @danycontre for your work here.

As discussed on our team call yesterday myself, @ejhenry & @mblant agreed the following that will require changes to this PR:

1. In the `/parameters` folder for each module have a parameter file for the `min` and `max`
     1. Rename `min` from `<module>.minimum.parameters.example.json` to `<module>.min.parameters.json` for all modules
     2. Rename `max` from  `<module>.parameters.example.json` to `<module>.max.parameters.json`
2. Update all docs with new references
    1. Each modules `README.md` deployment instructions
    2. Contribution guide instructions - https://github.com/Azure/ALZ-Bicep/blob/main/docs/wiki/Contributing.md#constructing-a-bicep-module
3. Update E2E ADO Tests where appropriate - https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/bicep-build-to-validate.yml
    1. @jfaurskov can help if any clarity needed 👍

Thanks and appreciate this is a lot of work, so any blockers or assistance needed, just let me know 

Thanks

Jack

**Comment by jtracey93** [comment]
not stale @danycontre is busy on another project launch ATM

**Comment by rjygraham** [comment]
@jtracey93 I'd like to propose the following file names for parameters:

Keep for min parameter files:
- Rename min from `<module>.minimum.parameters.example.json` to `<module>.min.parameters.json` for all modules

Consider one of the following for the complete parameter files:
- Rename ~~max~~ **all** from `<module>.parameters.example.json` to `<module>.all.parameters.json`
- Rename ~~max~~ **complete** from `<module>.parameters.example.json` to `<module>.complete.parameters.json`
- Rename ~~max~~ **full** from `<module>.parameters.example.json` to `<module>.full.parameters.json`

**Comment by jtracey93** [comment]
Agreed on min and I like all for the complete option. 

@jfaurskov thoughts?

**Comment by rjygraham** [comment]
@jtracey93 @jfaurskov I edited my comment regarding a completely different convention as I worked my way into the policy and role modules. Please see updated comment. I'm onboard with "complete" for all parameters.

**Comment by jtracey93** [comment]
I like. Do we want min or all at the front to help quickly chose the correct one ?

**Comment by rjygraham** [comment]
This goes back to the personal preference piece. I personally would prefer having the files grouped by like functionality vs complete vs min parameter files, but to each their own.

It's the difference between this:

- `roleAssignmentManagementGroup.managedIdentity.parameters.complete.json`
- `roleAssignmentManagementGroup.managedIdentity.parameters.min.json`
- `roleAssignmentManagementGroup.securityGroup.parameters.complete.json`
- `roleAssignmentManagementGroup.securityGroup.parameters.min.json`
- `roleAssignmentManagementGroup.servicePrincipal.parameters.complete.json`
- `roleAssignmentManagementGroup.servicePrincipal.parameters.min.json`

And this:

- `roleAssignmentManagementGroup.complete.managedIdentity.parameters.json`
- `roleAssignmentManagementGroup.complete.securityGroup.parameters.json`
- `roleAssignmentManagementGroup.complete.servicePrincipal.parameters.json`
- `roleAssignmentManagementGroup.min.managedIdentity.parameters.json`
- `roleAssignmentManagementGroup.min.securityGroup.parameters.json`
- `roleAssignmentManagementGroup.min.servicePrincipal.parameters.json`

**Comment by rjygraham** [comment]
Additionally, for modules that only contain a single set of complete & min parameter files, having the min complete designation at the end of the file name is more user-friendly if you want to test between the two... cursor only needs to move a few characters. 😜 #LazyDev

**Comment by jfaurskov** [comment]
> Agreed on min and I like all for the complete option.
> 
> @jfaurskov thoughts?

Sounds good to me :-)

**Comment by jtracey93** [comment]
Closing as #227 supersedes this

**Pull request closed without merging**
