### PR TITLE
Added newer linter-rules

### PR DESCRIPTION
**Pull request by picccard**
# Overview/Summary

Newer [bicep releases](https://github.com/Azure/bicep/releases/tag/v0.29.45) adds more linter rules.
This PR adds the missing rules from [the example linter-config](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/bicep-config-linter).

If the rules should be error/warning/off...etc. might be changed...

This could potentially be a breaking change.

## This PR fixes/adds/changes/removes

1. Adds more linter rules with default level from the example on ms-docs

### Breaking Changes
Could potentially break deployments of customer custom-module
~Could potentially break deployments of internal bicep files~
No error on any .bicep in ALZ-Bicep repo found, fixes for new warnings in #827 

## Testing Evidence

Linter in VSCode reports no errors. Warnings is fixed in PR #827

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://github.com/Azure/ALZ-Bicep/wiki/Contributing) and ensured this PR is compliant with the guide
- [ ] Ensured the resource API versions in `.bicep` file/s I am adding/editing are using the latest API version possible
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/ALZ-Bicep/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/ALZ-Bicep/issues)
- [ ] *(ALZ Bicep Core Team Only)* Associated it with relevant [ADO Items](https://aka.ms/alz/bicep/backlog)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/ALZ-Bicep/tree/main)
- [ ] Performed testing and provided evidence.
- [ ] Updated one or more of the following tests *(if required)*
  - [Unit](https://github.com/Azure/ALZ-Bicep/blob/main/.github/workflows/bicep-build-to-validate.yml)
  - [Linting](https://github.com/Azure/ALZ-Bicep/tree/main/.github/workflows)
  - [E2E (End-To-End)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/bicep-build-to-validate.yml)
  - [ValidateAzCloud (Base validation in Azure Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/base-unit-validate.yml)
  - [ValidateMcCloud (Base validation in Azure China Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/mc-base-unit-validate.yml)
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Module READMEs, Wiki Docs etc.)
- [ ] If relevant, created or updated Code Tours [here](https://github.com/Azure/ALZ-Bicep/blob/main/.vscode/tours)

### CODE REVIEW

**Comment by picccard** [comment]
Tests fails on the link checker... 💀

**Review by oZakari — APPROVED** [review]
Thanks @picccard!! I just changed the `no-deployments-resources` to error but otherwise I agree with the other levels you incorporated.

**Pull request merged**
