### PR TITLE
Issue #416 - Link description in policy definitions for China

### LINKED ISSUE #416: ❓👂 Question/Feedback - Incorrect link description in Wiki page for Policy Definitions
## Question/Feedback

In the wiki for the Policy Definitions, under the parameters, the second link description says [Parameters for Azure Commercial Cloud](https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/policy/definitions/generateddocs/mc-customPolicyDefinitions.bicep.md), but this redirects to the parameters for the China Regions. Direct link to the parameters heading:

https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/policy/definitions/README.md#parameters

## Possible Answers/Solutions?

The description should be changed to something like ***Parameters for China Regions***

### PR DESCRIPTION
**Pull request by JamJarchitect**
# Overview/Summary

Replaced link description as duplicate commercial cloud instead of one commercial, one for china

## This PR fixes/adds/changes/removes

1. Link definition in policy definitions module readme to go to mooncake parameters.
2. Fixes #416 & [AB#25662](https://dev.azure.com/CSUSolEng/2a9d5a5a-8998-4ad0-81c8-ef3045e4da97/_workitems/edit/25662)

### Breaking Changes

1. N/A

## Testing Evidence

N/A

## As part of this Pull Request I have

- [X] Read the [Contribution Guide](https://github.com/Azure/ALZ-Bicep/wiki/Contributing) and ensured this PR is compliant with the guide
- [X] Ensured the resource API versions in `.bicep` file/s I am adding/editing are using the latest API version possible
- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/ALZ-Bicep/pulls)
- [X] Associated it with relevant [GitHub Issues](https://github.com/Azure/ALZ-Bicep/issues)
- [X] *(ALZ Bicep Core Team Only)* Associated it with relevant [ADO Items](https://aka.ms/alz/bicep/backlog)
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/ALZ-Bicep/tree/main)
- [X] Performed testing and provided evidence.
- [X] Updated one or more of the following tests *(if required)*
  - [Unit](https://github.com/Azure/ALZ-Bicep/blob/main/.github/workflows/bicep-build-to-validate.yml)
  - [Linting](https://github.com/Azure/ALZ-Bicep/tree/main/.github/workflows)
  - [E2E (End-To-End)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/bicep-build-to-validate.yml)
  - [ValidateAzCloud (Base validation in Azure Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/base-unit-validate.yml)
  - [ValidateMcCloud (Base validation in Azure China Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/mc-base-unit-validate.yml)
- [X] Updated relevant and associated documentation (e.g. Contribution Guide, Module READMEs, Wiki Docs etc.)
- [X] If relevant, created or updated Code Tours [here](https://github.com/Azure/ALZ-Bicep/blob/main/.vscode/tours)

### CODE REVIEW

**Review by jfaurskov — DISMISSED** [review]
LGTM

**Review by jtracey93 — CHANGES_REQUESTED** [review]
Thanks @JamJarchitect I found a couple of other instances of this bug to change:

- https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/roleAssignments/README.md
- https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/policy/assignments/alzDefaults/README.md

**Comment by JamJarchitect** [comment]
> Thanks @JamJarchitect I found a couple of other instances of this bug to change:
> 
> * https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/roleAssignments/README.md
> * https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/policy/assignments/alzDefaults/README.md

Now it get's interesting! 

- `roleAssignments` uses the same Bicep module for both Commercial and China from the looks of things. I will amend the parameter link to say `Link to parameters' or something to that effect with mentioning default Mooncake parameters.
- The `policy/assignments/alzDefaults` has parameter files for china, but not a separate module. I'll do the same as above and mention that default Mooncake parameters are available too.

Thoughts @jtracey93 ?

**Comment by JamJarchitect** [comment]
> > Thanks @JamJarchitect I found a couple of other instances of this bug to change:
> > 
> > * https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/roleAssignments/README.md
> > * https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/policy/assignments/alzDefaults/README.md
> 
> Now it get's interesting!
> 
> * `roleAssignments` uses the same Bicep module for both Commercial and China from the looks of things. I will amend the parameter link to say `Link to parameters' or something to that effect with mentioning default Mooncake parameters.
> * The `policy/assignments/alzDefaults` has parameter files for china, but not a separate module. I'll do the same as above and mention that default Mooncake parameters are available too.
> 
> Thoughts @jtracey93 ?

Separate module for Mooncake exists `mc-alzDefaultPolicyAssignments` so I've amended the parameter link description to reflect accordingly!

**Comment by jtracey93** [comment]
@JamJarchitect is this good for re-review?

**Comment by JamJarchitect** [comment]
> @JamJarchitect is this good for re-review?

I'm just debating a last couple of bits.

I'm think to put a note in each of the parameters section just stating that the module CAN be used in Mooncake, but there is no dedicated module for it, but we have example parameters in the folder - it'll just clear up any confusion.

Thoughts?

**Comment by jtracey93** [comment]
Sounds good





________________________________

**Comment by JamJarchitect** [comment]
> Sounds good

Should be ready for review now. Updated the links to the markdowns appropriately and put a note in about the modules and Azure China

**Review by jtracey93 — APPROVED** [review]
LGTM

**Pull request merged**
