### PR TITLE
feat: Add SNAT property to firewall resources

### LINKED ISSUE #739: Add support for Firewall Policy SNAT parameter
### Describe the feature end to end, including deployment scenario details under which the feature would occur.

The resource `firewallPolicies` does not currently support the parameter `snat`. 

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

Adding "Manually specified IP ranges" to SNAT Exceptions in Azure Portal works fine. But since this is a property of the Firewall Policy this configuration will be removed during redeployment of the hubNetworking-module.

### Please provide the correlation id associated with your error or bug.

_No response_

### Can you describe any alternatives that you have taken since this feature does not exist?

Only option I see as of now is to manually re-add configuration in portal, after hubNetworking as been deployed.
Another option would be to deploy a Route Server, and auto-learn private ranges. But it is not desirable to introduce a new paid resource, and dynamic routing, to solve this minor issue.

### Feature Implementation

_No response_

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by oZakari**
# Overview/Summary

Add SNAT property to firewall resources

## Related Issues/Work Items

Closes #739 

## This PR fixes/adds/changes/removes

1. Add SNAT property to firewall resources

### Breaking Changes
None

## Testing Evidence

Replace this with any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://github.com/Azure/ALZ-Bicep/wiki/Contributing) and ensured this PR is compliant with the guide
- [x] Ensured the resource API versions in `.bicep` file/s I am adding/editing are using the latest API version possible
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/ALZ-Bicep/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/ALZ-Bicep/issues)
- [x] *(ALZ Bicep Core Team Only)* Associated it with relevant [ADO Items](https://aka.ms/alz/bicep/backlog)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/ALZ-Bicep/tree/main)
- [x] Performed testing and provided evidence.
- [ ] Updated one or more of the following tests *(if required)*
  - [Unit](https://github.com/Azure/ALZ-Bicep/blob/main/.github/workflows/bicep-build-to-validate.yml)
  - [Linting](https://github.com/Azure/ALZ-Bicep/tree/main/.github/workflows)
  - [E2E (End-To-End)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/bicep-build-to-validate.yml)
  - [ValidateAzCloud (Base validation in Azure Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/base-unit-validate.yml)
  - [ValidateMcCloud (Base validation in Azure China Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/mc-base-unit-validate.yml)
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Module READMEs, Wiki Docs etc.)
- [ ] If relevant, created or updated Code Tours [here](https://github.com/Azure/ALZ-Bicep/blob/main/.vscode/tours)

### CODE REVIEW

**Comment by oZakari** [comment]
\azp validate azcloud

**Review by jtracey93 — APPROVED** [review]

**Pull request merged**
