### PR TITLE
Add Various Features & Fix Various Bugs to VWAN & Hub Networking

### LINKED ISSUE #205: 💡 Feature Request - Add AZ Support for Azure Firewall in Secure vHub Model - `vwanConnectivity.bicep`
## Describe the solution you'd like

AZs are now supported for Azure Firewalls deployed in the Secure vHub model (Virtual WAN) as per https://azure.microsoft.com/en-us/blog/boost-your-network-security-with-new-updates-to-azure-firewall & https://docs.microsoft.com/en-us/azure/virtual-wan/virtual-wan-faq#how-are-availability-zones-and-resiliency-handled-in-virtual-wan

This change looks to be to add the `zones` property to the Azure Firewall in `vwanConnectivity.bicep` and expose as a parameter and default to a sensible value (TBC)

## Describe alternatives you've considered

N/A

## Additional context

This is also being done in the ALZ Accelerator https://github.com/Azure/Enterprise-Scale/issues/955

### LINKED ISSUE #219: Azure Firewall with Virtual Hub deployment fails as unable to set Public IP
https://github.com/Azure/ALZ-Bicep/blob/efa25290d42e92ab6ae88ad8903d443facb541f5/infra-as-code/bicep/modules/vwanConnectivity/vwanConnectivity.bicep#L169

This does not work with Virtual Hubs, it appears the Public IP is a read only resource that gets randomly allocated?

### LINKED ISSUE #225: 💡 Feature Request - VWAN Route Table Missing In VWAN If Deploy Azure Firewall in Secure Hub Model
## Describe the solution you'd like

Add configuration of VWAN Route Table in VWAN If Deploying Azure Firewall in Secure Hub Model 

## Describe alternatives you've considered

N/A

## Additional context

N/A

### PR DESCRIPTION
**Pull request by jtracey93**
# Overview/Summary

Add Various Features & Fix Various Bugs to VWAN & Hub Networking

## This PR fixes/adds/changes/removes

1. Fixes #205 for both VWAN & Hub/Spoke model
2. Fixes #219 
3. Fixes #225 
4. Add Firewall Policy to Hub/Spoke model
5. Added AZ support to `publicIp` module
6. Updated `bicepconfig.json` for `vwanConnectivity.bicep` as added DNS zones
7. Add Private DNS Zones to `vwanConnectivity.bicep`
8. Add DDoS Std Plan to `vwanConnectivity.bicep`

### Breaking Changes

1. Renamed `parHubVirtualNetworkId` to `parVirtualNetworkIdToLink` in `privateDnsZones.bicep` module

## Testing Evidence

image
image
image
image
image

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://github.com/Azure/ALZ-Bicep/wiki/Contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/ALZ-Bicep/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/ALZ-Bicep/issues)
- [x] *(ALZ Bicep Core Team Only)* Associated it with relevant [ADO Items](https://aka.ms/alz/bicep/backlog)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/ALZ-Bicep/tree/main)
- [x] Performed testing and provided evidence.
- [ ] Updated tests *(if required)* [Unit](https://github.com/Azure/ALZ-Bicep/blob/main/.github/workflows/bicep-build-to-validate.yml) - [Linting](https://github.com/Azure/ALZ-Bicep/tree/main/.github/workflows) - [E2E (End-To-End)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/bicep-build-to-validate.yml)
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Module READMEs, Wiki Docs etc.)
- [ ] If relevant, created or updated Code Tours [here](https://github.com/Azure/ALZ-Bicep/blob/main/.vscode/tours)

### CODE REVIEW

**Review by JamJarchitect — APPROVED** [review]
LGTM

**Review by jfaurskov — CHANGES_REQUESTED** [review]

**Review by jfaurskov — APPROVED** [review]
LGTM

**Comment by jtracey93** [comment]
E2E checks being ignored as manually tested and evidenced in PR by @jtracey93

Markdown link checks being ignored due to false positives

**Pull request merged**
